lint: {}
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Alexander Nater
  description: Pipeline for assembly evaluation
  force: false
  is_nfcore: true
  name: asseval
  org: nf-core
  outdir: .
  version: 1.0.0dev
