bump_version: null
lint: {}
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Alexander Nater
  description: Pipeline for assembly evaluation
  force: true
  is_nfcore: true
  name: asseval
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0dev
update: null
